server:
  port: 7979

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: category_route
          uri: lb://CATEGORY
          predicates:
            - Path=/category/**
        - id: product_route
          uri: lb://PRODUCT
          predicates:
            - Path=/product/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

