server:
  port: 8888

spring:
  application:
    name: USERS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

ORDERS:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule